#    VSM_notice_begin
#
#      VSM - Versity Storage Management File System
#
#		Copyright (c) 2015 Versity, Inc. All Rights Reserved.
#
#    VSM_notice_end

DEPTH = ..

include $(DEPTH)/mk/common.mk

DIRS = interface cmd

include $(DEPTH)/mk/targets.mk
include $(DEPTH)/mk/depend.mk
